### ISSUE TITLE
Troubles in ReactJS

### ISSUE THREAD

**Issue by SebasMag** [jgravois/bootstrap-geocoder#3]
Hi john ! , im trying to use this plugin in react but im getting some troubles ....
First,  i copied the GeosearchInput.js in my project , then i imported the file into my component like this:
 `import SearchInput from './GeosearchInput'`   .
after that i tried to use is like this : 
```
const map = mapRef.leafletElement
 var search = SearchInput({ inputTag: 'address' , placeholder: 'Address here' }).addTo(map)

```
in my JSX i have a input with id = address.
When i run my app the input shows the placeholder 'Address here', so i can think that its successfully linked, but when i start typing for an address i got this error: 
`TypeError: this._control._clearProviderSuggestions is not a function`

Thanks !!

**Comment by jgravois** [comment]
as popular as it is, React isn't a framework I often touch, but from the sounds of it the error has something to do with the interplay between Esri Leaflet Geocoder's core class and this plugin.

https://github.com/Esri/esri-leaflet-geocoder/blob/master/src/Classes/GeosearchCore.js

given that you are attempting to import the raw ES6 code from this plugin instead of using the compiled output that bundles it alongside Esri Leaflet and Esri Leaflet Geocoder, the first thing I'd be curious to know is whether your project is also bundling ES6 code from the other two plugins.

I'd need to see a stripped down, ready to `npm install` repro case in order to poke at this and try and help you further.

**Comment by SebasMag** [comment]
John thanks for your quick answer, I am actually using esri-leaflet-geocoder  in the input attached to the map and it works just fine. 
 In the same file i import GeosearchInput  i also import react-leaflet and esri-leaflet-geocoder.

do u think that if i use the compiled output it will solve my problem?

**Comment by SebasMag** [comment]
![image](https://user-images.githubusercontent.com/38332255/74350450-829c4780-4d94-11ea-9a22-f0ea9753fbce.png)

Here is a image of the error that im getting

**Comment by jgravois** [comment]
> do u think that if i use the compiled output it will solve my problem?

🤷‍♂
